yml

diff --git a/.github/workflows/adhoc.yml b/.github/workflows/adhoc.yml
--- a/.github/workflows/adhoc.yml
+++ b/.github/workflows/adhoc.yml
@@ -17,16 +17,16 @@ jobs:
         with:
           submodules: true
 
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 3.1
+      # - name: Set up Ruby
+      #   uses: ruby/setup-ruby@v1
+      #   with:
+      #     ruby-version: 3.1
 
-      - name: Set Xcode version
-        run: |
-          sudo xcode-select -s /Applications/Xcode26.0.1.app/Contents/Developer || true
-          echo "Xcode version:"
-          xcodebuild -version
+      # - name: Set Xcode version
+      #   run: |
+      #     sudo xcode-select -s /Applications/Xcode26.0.1.app/Contents/Developer || true
+      #     echo "Xcode version:"
+      #     xcodebuild -version
 
       # - name: Install dependencies
       #   run: |
@@ -61,11 +61,11 @@ jobs:
       #     echo "PROFILE_NAME=$PROFILE_NAME" >> $GITHUB_ENV
 
       - name: Archive
-        # working-directory: SwiftTest
+        working-directory: swift-test
         # env:
         #   DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
         run: |
-          xcodebuild archive -workspace /Users/liangzhang/swift-test/SwiftTest.xcworkspace \
+          xcodebuild archive -workspace SwiftTest.xcworkspace \
             -scheme SwiftTest \
             -configuration AdHoc \
             -archivePath /Users/liangzhang/Desktop/pms_adhoc/SwiftTest.xcarchive \
@@ -89,12 +89,12 @@ jobs:
       #     name: pms-ipa
       #     path: SwiftTest/build/output/*.ipa
 
-      - name: Cleanup keychain
-        if: always()
-        env:
-          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-        run: |
-          security delete-keychain ios-build.keychain || true
+      # - name: Cleanup keychain
+      #   if: always()
+      #   env:
+      #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+      #   run: |
+      #     security delete-keychain ios-build.keychain || true
 
 # Required repository secrets:
 # - IOS_SIGNING_P12: base64-encoded .p12 certificate
